### ISSUE TITLE
Making a shareable link icon optional.

### ISSUE THREAD

**Issue by howardm** [ncase/nutshell#25]
Hi,

Thanks so much for this great utility!  I'm exploring the use of the Quarto extension.

My question: In relation to the image below, is it possible to make the default display of the shareable icon optional ?

![Screen Shot 2023-01-25 at 5 07 27 PM](https://user-images.githubusercontent.com/6101226/214723730-b8af7f6c-f9dd-49e4-9211-84be35544ef4.jpg)

Cheers.

Howard

**Comment by ncase** [comment]
Thank you for the kind words, Howard!  I'm very honored to see Nutshell being used in scientific publishing!

I have implemented your suggestion in the latest release. (which is still at `https://cdn.jsdelivr.net/gh/ncase/nutshell/nutshell.js`, if you're including it externally)  To turn off the share-icon, type:

```
<script>
Nutshell.setOptions({
    dontEmbedHeadings: true
});
</script>
```
after including the Nutshell.js file. More details in [the updated Advanced Features documentation](https://github.com/ncase/nutshell/blob/main/README.md#advanced-features--options).

Thank you again! 🎉  Best wishes in helping your readers learn the difference between the various terrifying lung edemas.

**Comment by howardm** [comment]
Thanks.

I installed it via this extension:  https://github.com/schochastics/quarto-nutshell

Please explain in simple terms how to turn off the Share icon given my setup.

FYI -- here is a screenshot of my RStudio setup:

![Screen Shot 2023-02-01 at 10 32 23 AM](https://user-images.githubusercontent.com/6101226/216119482-394bfc59-f6c3-4490-84d9-321b1435981c.jpg)

Howard

**Comment by ncase** [comment]
Ah, alas, I did not create that extension, so you'd have to ask its creator, `schochastics`.  I also have never worked with RStudio or Quarto before.

A workaround I suggest is adding custom style (CSS) to your app. I've never used RStudio or Quarto before, so I don't know exactly how to do it, but a quick web search of "custom CSS RStudio/Quarto" got me these two links:

* https://shiny.rstudio.com/articles/css.html
* https://stackoverflow.com/questions/74026514/how-to-apply-css-style-to-quarto-output

The CSS you'd need to add is just one line:

`.nutshell-heading-embed{ display:none; }`

That should hide the share button. Good luck!

**Comment by howardm** [comment]
That works!

Thanks so much !
