### ISSUE TITLE
URL for nutshell.js includes not-yet-existent version number 1.0.0

### ISSUE THREAD

**Issue by mkosma** [ncase/nutshell#4]
FYI the nutshell.js link on ncase.me includes `nutshell@1.0.0` specifying a release that doesn't yet exist (404 err). Removing the `@1.0.0` seems to help...

monty

**Comment by ncase** [comment]
Aggghhhh of course I'd have an obvious error the day I ship. I forgot to make a release on this repo, activating JSDeliver.

It should work now! I even released version 1.0.1: https://github.com/ncase/nutshell/releases/tag/1.0.1

Thanks for catching this, @mkosma !
