### ISSUE TITLE
Minified version returns a 404

### ISSUE THREAD

**Issue by melat0nin** [ncase/nutshell#9]
`https://cdn.jsdelivr.net/gh/ncase/nutshell@1.0.0/nutshell.min.js` currently returns a 404.

**Comment by ncase** [comment]
Thanks for catching this @melat0nin ! Weirdly, I can't get JSDeliver to recompile a minified version for 1.0.0 . So I just pushed up a new release for version 1.0.1, and the new minified link works, at least:

[https://cdn.jsdelivr.net/gh/ncase/nutshell@1.0.1/nutshell.min.js](https://cdn.jsdelivr.net/gh/ncase/nutshell@1.0.1/nutshell.min.js)

Can't get earlier one to work, though. :/
